### ISSUE TITLE
How to integrate Payhere SDK into react native expo

### ISSUE THREAD

**Issue by Ayomal98** [PayHereLK/payhere-mobilesdk-reactnative#10]

**Comment by PayHereDevs** [comment]
Hello @Ayomal98, apologies that we couldn't get back to you in time. Unfortunately this SDK cannot be used with React Native Expo. 

The reason is that React Native Expo does not support native Android & iOS code. This PayHere SDK relies on the [PayHere Android SDK](https://support.payhere.lk/api-&-mobile-sdk/payhere-android) and [PayHere iOS SDK](https://support.payhere.lk/api-&-mobile-sdk/payhere-ios) and those dependencies are not available when running through Expo.

We will be closing this issue for now because at the moment, there are no work arounds for getting the SDK to work with Expo. You will need to use the React Native CLI instead.
