### ISSUE TITLE
iOS build error

### ISSUE THREAD

**Issue by Januka** [PayHereLK/payhere-mobilesdk-reactnative#13]
Returning bellow error when try to run the app.
`Undefined symbols for architecture x86_64:
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libAlamofire.a(NetworkReachabilityManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by PayHereDevs** [comment]
Hello @Januka, apologies that we couldn't get back to you in reasonable time. Please make sure you have run the following command in your project root folder.

```
npx react-native link @payhere/payhere-mobilesdk-reactnative
```

Running the above command should resolve issues with the SDK's dependencies not being linked correctly with CocoaPods. Please let us know if the issue persists, and we will be glad to be of further support.

**Comment by PayHereDevs** [comment]
We will be stating here a possible solution for future readers of this issue. If the solution fixed your issue, please provide some feedback so that we can close the issue with the accepted solution.

# Step 1: Add an Empty Swift File.

1. Open up your React Native iOS project's `.xcworkspace` file.
2. Go to the __File > New > File__ menu.
3. Click on the "ios" tab and select "Swift File"
4. Click Next, and enter a name such as "TestSwift.swift"
5. If you are prompted asking the creation of a "Bridging Header File", click __YES__.

If you were not prompted asking the creation of a Bridging Header File, follow these steps:

1. Press Command + Shift + O inside Xcode, and type in "Bridging".
2. See if you find a file name similar to "<App Name>-Bridging-Header.h" that is __NOT__ under the Pods folder.
3. If there is already such a file, **Step 1** is complete. Please go to **Step 2**. (. Otherwise go to File > New > File and create a new Header File (.h) named as follows.

- App-Bridging-Header.h

4. From the Left Panel (Project Navigator) in Xcode, Select the Top Most item. 
5. Select your iOS App target.
6. Click the "Build Settings" Tab.
7. Select the "All" information level.
8. Type in "Bridg" into the Search Panel.
9. Set the below properties and values.

<img src="https://user-images.githubusercontent.com/22514746/143024180-5648ff43-15c2-4f31-a9a4-2da0c33a7dad.png" width="400"/>

At this point, your Xcode window should look as follows.

<img src="https://user-images.githubusercontent.com/22514746/143024591-af7609ea-861e-4d45-a975-9451552d81f6.png" width="700"/>

[Image Link](https://user-images.githubusercontent.com/22514746/143024591-af7609ea-861e-4d45-a975-9451552d81f6.png)

# Step 2: Remove references to "swift-5.0/$(PLATFORM_NAME)"

1. Right click on the Top-Most item in your Xcode Project Navigator (left panel)
2. Select "Show in Finder"
3. On the ".xcodeproj" file that is highlighted in the Finder window, Right click on it.
4. Select "Show Package Contents"
5. Find the file named "project.pbxproj"
6. Right click on it, and open it with TextEdit.app
7. Inside Text Edit press Command + F (to open search mode)
8. Paste in the following text and press Enter.

```
"\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\\"",
```

Your TextEdit window should now look like this:

<img width="700"  max-width="100%" alt="TextEdit App Showing Search Result" src="https://user-images.githubusercontent.com/22514746/147973407-752d9bfc-1d4a-4a07-8626-d973b5fb2d6a.png">

9. Remove all traces of the above line from the `pbxproj` file.
10. Save the file.
11. Re-open the `.xcworkspace`.
12. Clean the project from the Project > Clean Build Folder menu item.
13. Re-build the project!
