### ISSUE TITLE
build failed after installing payhere mobile sdk 

### ISSUE THREAD

**Issue by sajas-nm** [PayHereLK/payhere-mobilesdk-reactnative#5]
`A problem occurred configuring project ':@payhere_payhere-mobilesdk-reactnative'.
> No signature of method: org.apache.groovy.json.internal.LazyMap.split() is applicable for argument types: (String) values: [ ]
  Possible solutions: split(groovy.lang.Closure), wait(), sort(), wait(long), put(java.lang.String, java.lang.Object), print(java.io.PrintWriter)`

**Comment by PayHereDevs** [comment]
Hi Sajas!

This issue has been fixed in the latest version of the PayHere React Native SDK, 1.0.8. You can install it using the following command.

     npm install @payhere/payhere-mobilesdk-reactnative@1.0.8

To provide some insight into what went wrong, the issue was with the `build.gradle` script trying to extract the `author` field from `package.json`. This is no longer being performed as the authors are hardcoded into the `build.gradle` file.
